---
title: "Tipping_Minority"
author: "Jordan Everall"
date: '2023-05-04'
output: html_document
---



```{r setup, include=FALSE}
library(dplyr)
library(ggplot2)


path <- dirname(rstudioapi::getSourceEditorContext()$path)
knitr::opts_chunk$set(echo = TRUE)
```


```{r data in}
#path <- paste0("../", path)

# Function to import csv files
import_csv_files <- function(directory) {
  # List all csv files in the directory
  files <- list.files(directory, pattern="*.csv")
  
  # Use lapply to apply a function to all files
  file_list <- lapply(files, function(x){
    read.csv(file.path(directory, x), sep = ",")
  })
  
  # Name the list elements with the names of the files (without extension)
  names(file_list) <- tools::file_path_sans_ext(files)
  
  # Return the list of dataframes
  return(file_list)
}


csv_files <- import_csv_files("C:\\Users\\everall\\Documents\\Papers\\Tipping_Minority\\Code\\Data\\Experimental")

#csv_files <- import_csv_files("./Data/Experimental")

# Now, you can access each file like this:
# df1 <- csv_files[['filename1']]






```

## Including Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE}
plot(pressure)
```
